package com.me.fall2018.assignment3.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "course")
public class Course {

	private String id;
	private String courseId;
	private String profId;
	private String taId;
	private String department;
	private String boardId;
	private List<String> roster;
	private String notificationTopic;
	
	public Course() {}
	
	public Course(String id, String courseId, String profId, String taId, String department, String boardId, List<String> roster,String notificationTopic) {
		this.id = id;
		this.courseId = courseId;
		this.profId = profId;
		this.taId = taId;
		this.department = department;
		this.boardId = boardId;
		this.roster = roster;
		this.notificationTopic = notificationTopic;
	}
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBIndexHashKey(attributeName = "courseId",globalSecondaryIndexName = "courseId")
	public String getCourseId() {
		return courseId;
	}
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
	
	@DynamoDBAttribute(attributeName = "profId")
	public String getProfId() {
		return profId;
	}
	public void setProfId(String profId) {
		this.profId = profId;
	}
	
	@DynamoDBAttribute(attributeName = "taId")
	public String getTaId() {
		return taId;
	}
	public void setTaId(String taId) {
		this.taId = taId;
	}
	
	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	
	@DynamoDBAttribute(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}
	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}
	
	@DynamoDBAttribute(attributeName = "roster")
	public List<String> getRoster() {
		return roster;
	}
	public void setRoster(List<String> roster) {
		this.roster = roster;
	}

	@DynamoDBAttribute(attributeName = "notificationTopic")
	public String getNotificationTopic() {
		return notificationTopic;
	}

	public void setNotificationTopic(String notificationTopic) {
		this.notificationTopic = notificationTopic;
	}
	
}
